name: CI - Build Container and Update Manifest Repo

on:
  push:
    branches:
      - master
  # Run builds for any PRs.
  pull_request:

env:
  IMAGE_NAME: nstogner/hello-go-api

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_SHA::8}
    - name: Login to Dockerhub
      if: github.event_name == 'push'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push the Docker image
      run: docker push $IMAGE_NAME:${GITHUB_SHA::8}

  # Deploy by updating GitOps manifests with new image tag.
  patch-push-manifest:
    # Ensure build job passes before updating deployment.
    needs: build-push-image
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: nstogner/k8s-sample-apps
    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl
        chmod +x ./kubectl
    - name: Patch
      run: |
        export NEW_IMAGE="$IMAGE_NAME:${GITHUB_SHA::8}"
        export PATCH=$(echo '{"spec":{"template":{"spec":{"containers":[{"name":"hello-api","image":"$NEW_IMAGE"}]}}}}' | envsubst)
        echo "PATCH = $PATCH"
        ./kubectl patch --local -f ./hello-api/deployment.yaml -p $PATCH -o yaml > patch.yaml
        mv patch.yaml ./hello-api/deployment.yaml
    - name: Commit Changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN_MANIFESTS }}
      run: |
        git config --global user.email nicholas.stogner@gmail.com
        git config --global user.name "Nick Stogner"
        git diff
        git add ./hello-api/deployment.yaml
        git commit -m "Automated image tag update from github.com/${{ github.repository }} github actions CI job"
        export REMOTE_REPO="https://nstogner:${TOKEN}@github.com/nstogner/k8s-sample-apps.git"
        git push "${REMOTE_REPO}" HEAD:master
