name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nstogner/hello-go-api:latest
    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push the Docker image
      run: docker push nstogner/hello-go-api:latest
