name: Docker Image CI

on:
  push:
    branches:
      - master
  # Run builds for any PRs.
  pull_request:

env:
  IMAGE_NAME: nstogner/hello-go-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_SHA::8}
    - name: Login to Dockerhub
      if: github.event_name == 'push'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push the Docker image
      run: docker push $IMAGE_NAME:${GITHUB_SHA::8}
  deploy:
    # Ensure build job passes before updating deployment.
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: nstogner/k8s-sample-apps
    - uses: azure/setup-kubectl@v1
      with:
        version: '1.16.2'
      id: install
    - name: Patch
      run: kubectl patch --local -f ./hello-api/deployment.yaml -p '{"spec":{"template":{"spec":{"containers":[{"name":"hello-api","image":"$IMAGE_NAME:${GITHUB_SHA::8}"}]}}}}' -o yaml
      
